In [6]:
import xarray as xr

/g/data/r87/dbi599/miniconda3/envs/ocean/lib/python3.6/site-packages/dask/config.py:131: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}


In [45]:
import iris

In [70]:
import cf_units

In [1]:
import glob

In [2]:
infile_list = glob.glob('/g/data/p66/cm2704/archive/bj594/history/ocn/ocean_month.nc-*')

In [4]:
infile_list.sort()

## Iris

In [8]:
cube = iris.load_cube(infile, 'implicit vert diffusion of heat')

/g/data/r87/dbi599/miniconda3/envs/ocean/lib/python3.6/site-packages/iris/fileformats/cf.py:1033: UserWarning: Ignoring variable 'geolon_c' referenced by variable 'tx_trans_int_z': Dimensions ('yu_ocean', 'xu_ocean') do not span ('time', 'yt_ocean', 'xu_ocean')
  warnings.warn(msg)
/g/data/r87/dbi599/miniconda3/envs/ocean/lib/python3.6/site-packages/iris/fileformats/cf.py:1033: UserWarning: Ignoring variable 'geolat_t' referenced by variable 'tx_trans_int_z': Dimensions ('yt_ocean', 'xt_ocean') do not span ('time', 'yt_ocean', 'xu_ocean')
  warnings.warn(msg)
/g/data/r87/dbi599/miniconda3/envs/ocean/lib/python3.6/site-packages/iris/fileformats/cf.py:1033: UserWarning: Ignoring variable 'geolat_c' referenced by variable 'salt_merid_flux_gyre_pacific': Dimensions ('yu_ocean', 'xu_ocean') do not span ('time', 'yu_ocean')
  warnings.warn(msg)
/g/data/r87/dbi599/miniconda3/envs/ocean/lib/python3.6/site-packages/iris/fileformats/cf.py:1033: UserWarning: Ignoring variable 'geolon_c' reference

/g/data/r87/dbi599/miniconda3/envs/ocean/lib/python3.6/site-packages/iris/fileformats/cf.py:1033: UserWarning: Ignoring variable 'geolat_c' referenced by variable 'salt_merid_flux_gyre_arctic': Dimensions ('yu_ocean', 'xu_ocean') do not span ('time', 'yu_ocean')
  warnings.warn(msg)
/g/data/r87/dbi599/miniconda3/envs/ocean/lib/python3.6/site-packages/iris/fileformats/cf.py:1033: UserWarning: Ignoring variable 'geolon_c' referenced by variable 'temp_xflux_submeso_int_z': Dimensions ('yu_ocean', 'xu_ocean') do not span ('time', 'yt_ocean', 'xu_ocean')
  warnings.warn(msg)
/g/data/r87/dbi599/miniconda3/envs/ocean/lib/python3.6/site-packages/iris/fileformats/cf.py:1033: UserWarning: Ignoring variable 'geolat_t' referenced by variable 'temp_xflux_submeso_int_z': Dimensions ('yt_ocean', 'xt_ocean') do not span ('time', 'yt_ocean', 'xu_ocean')
  warnings.warn(msg)
/g/data/r87/dbi599/miniconda3/envs/ocean/lib/python3.6/site-packages/iris/fileformats/cf.py:1033: UserWarning: Ignoring variable '

/g/data/r87/dbi599/miniconda3/envs/ocean/lib/python3.6/site-packages/iris/fileformats/cf.py:1033: UserWarning: Ignoring variable 'geolat_c' referenced by variable 'temp_merid_flux_over_global': Dimensions ('yu_ocean', 'xu_ocean') do not span ('time', 'yu_ocean')
  warnings.warn(msg)
/g/data/r87/dbi599/miniconda3/envs/ocean/lib/python3.6/site-packages/iris/fileformats/cf.py:1033: UserWarning: Ignoring variable 'geolon_c' referenced by variable 'tx_trans_gm': Dimensions ('yu_ocean', 'xu_ocean') do not span ('time', 'st_ocean', 'yt_ocean', 'xu_ocean')
  warnings.warn(msg)
/g/data/r87/dbi599/miniconda3/envs/ocean/lib/python3.6/site-packages/iris/fileformats/cf.py:1033: UserWarning: Ignoring variable 'geolat_t' referenced by variable 'tx_trans_gm': Dimensions ('yt_ocean', 'xt_ocean') do not span ('time', 'st_ocean', 'yt_ocean', 'xu_ocean')
  warnings.warn(msg)
/g/data/r87/dbi599/miniconda3/envs/ocean/lib/python3.6/site-packages/iris/fileformats/cf.py:1033: UserWarning: Ignoring variable 'ge

/g/data/r87/dbi599/miniconda3/envs/ocean/lib/python3.6/site-packages/iris/fileformats/_pyke_rules/compiled_krb/fc_rules_cf_fc.py:1932: UserWarning: Ignoring netCDF variable 'f_vis' invalid units 'dimensionless'
  warnings.warn(msg)
/g/data/r87/dbi599/miniconda3/envs/ocean/lib/python3.6/site-packages/iris/fileformats/_pyke_rules/compiled_krb/fc_rules_cf_fc.py:1932: UserWarning: Ignoring netCDF variable 'bottom_salt' invalid units 'psu'
  warnings.warn(msg)
/g/data/r87/dbi599/miniconda3/envs/ocean/lib/python3.6/site-packages/iris/fileformats/_pyke_rules/compiled_krb/fc_rules_cf_fc.py:1932: UserWarning: Ignoring netCDF variable 'tide_speed_mask' invalid units 'dimensionless'
  warnings.warn(msg)
/g/data/r87/dbi599/miniconda3/envs/ocean/lib/python3.6/site-packages/iris/fileformats/_pyke_rules/compiled_krb/fc_rules_cf_fc.py:1932: UserWarning: Ignoring netCDF variable 'sw_frac' invalid units 'dimensionless'
  warnings.warn(msg)
/g/data/r87/dbi599/miniconda3/envs/ocean/lib/python3.6/site-pack

In [9]:
cube

<iris 'Cube' of implicit vert diffusion of heat / (Watts/m^2) (time: 6; tcell zstar depth: 50; latitude: 300; longitude: 360)>

In [10]:
coord_names = [coord.name() for coord in cube.dim_coords]

In [11]:
coord_names

['time', 'tcell zstar depth', 'latitude', 'longitude']

In [12]:
cube.coord('tcell zstar depth')

DimCoord(array([5.00000000e+00, 1.50000000e+01, 2.50000000e+01, 3.50000000e+01,
       4.50000000e+01, 5.50000000e+01, 6.50000000e+01, 7.50000000e+01,
       8.50000000e+01, 9.50000000e+01, 1.05000000e+02, 1.15000000e+02,
       1.25000000e+02, 1.35000000e+02, 1.45000000e+02, 1.55000000e+02,
       1.65000000e+02, 1.75000000e+02, 1.85000000e+02, 1.95000000e+02,
       2.05000000e+02, 2.16846756e+02, 2.41349014e+02, 2.80780731e+02,
       3.43250458e+02, 4.27315552e+02, 5.36715637e+02, 6.65414124e+02,
       8.12781616e+02, 9.69065125e+02, 1.13093494e+03, 1.28960461e+03,
       1.45577014e+03, 1.62292566e+03, 1.80155811e+03, 1.98485461e+03,
       2.18290479e+03, 2.38841748e+03, 2.61093506e+03, 2.84256445e+03,
       3.09220483e+03, 3.35129468e+03, 3.62805762e+03, 3.91326440e+03,
       4.21449512e+03, 4.52191797e+03, 4.84256592e+03, 5.16612988e+03,
       5.49924512e+03, 5.83129443e+03]), standard_name=None, units=Unit('meters'), long_name='tcell zstar depth', var_name='st_ocean', attr

In [14]:
cube.coord('tcell latitude')

CoordinateNotFoundError: 'Expected to find exactly 1 tcell latitude coordinate, but found none.'

## xarray

In [28]:
dset = xr.open_mfdataset(infile_list, decode_times=False)

In [29]:
dset

<xarray.Dataset>
Dimensions:                          (grid_xt_ocean: 360, grid_xu_ocean: 360, grid_yt_ocean: 300, grid_yu_ocean: 300, nv: 2, potrho: 80, potrho_edges: 81, st_edges_ocean: 51, st_ocean: 50, sw_edges_ocean: 51, sw_ocean: 50, time: 1980, xt_ocean: 360, xu_ocean: 360, yt_ocean: 300, yu_ocean: 300)
Coordinates:
  * xt_ocean                         (xt_ocean) float64 -279.5 -278.5 ... 79.5
  * yt_ocean                         (yt_ocean) float64 -77.88 -77.63 ... 89.77
  * nv                               (nv) float64 1.0 2.0
  * xu_ocean                         (xu_ocean) float64 -279.0 -278.0 ... 80.0
  * yu_ocean                         (yu_ocean) float64 -77.75 -77.51 ... 90.0
  * st_ocean                         (st_ocean) float64 5.0 15.0 ... 5.831e+03
  * st_edges_ocean                   (st_edges_ocean) float64 0.0 10.0 ... 6e+03
  * sw_ocean                         (sw_ocean) float64 10.0 20.0 ... 6e+03
  * sw_edges_ocean                   (sw_edges_ocean) float64 5.

In [31]:
dset['time']

<xarray.DataArray 'time' (time: 1980)>
array([1.55000e+01, 4.50000e+01, 7.45000e+01, ..., 6.01885e+04, 6.02190e+04,
       6.02495e+04])
Coordinates:
  * time     (time) float64 15.5 45.0 74.5 ... 6.019e+04 6.022e+04 6.025e+04
Attributes:
    long_name:       time
    units:           days since 1850-01-01 00:00:00
    cartesian_axis:  T
    calendar_type:   GREGORIAN
    calendar:        GREGORIAN
    bounds:          time_bounds

In [23]:
dset['temp'].data.max()

/g/data/r87/dbi599/miniconda3/envs/ocean/lib/python3.6/site-packages/numpy/core/_methods.py:28: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial)


nan

In [41]:
dset['geolat_t']

<xarray.DataArray 'geolat_t' (yt_ocean: 300, xt_ocean: 360)>
array([[-77.876625, -77.876625, -77.876625, ..., -77.876625, -77.876625,
        -77.876625],
       [-77.629715, -77.629715, -77.629715, ..., -77.629715, -77.629715,
        -77.629715],
       [-77.38171 , -77.38171 , -77.38171 , ..., -77.38171 , -77.38171 ,
        -77.38171 ],
       ...,
       [ 65.209656,  65.62409 ,  66.032196, ...,  66.032196,  65.62409 ,
         65.209656],
       [ 65.21018 ,  65.62565 ,  66.03475 , ...,  66.03475 ,  65.62565 ,
         65.21018 ],
       [ 65.21044 ,  65.62643 ,  66.03603 , ...,  66.03603 ,  65.62643 ,
         65.21044 ]], dtype=float32)
Coordinates:
  * xt_ocean  (xt_ocean) float64 -279.5 -278.5 -277.5 -276.5 ... 77.5 78.5 79.5
  * yt_ocean  (yt_ocean) float64 -77.88 -77.63 -77.38 ... 88.87 89.32 89.77
    geolat_t  (yt_ocean, xt_ocean) float32 -77.876625 -77.876625 ... 65.21044
    geolon_t  (yt_ocean, xt_ocean) float32 -279.5 -278.5 ... 79.973366 79.99112
Attributes:
    long

## New cube

In [48]:
ref_cube = iris.load_cube('/g/data/fs38/publications/CMIP6/CMIP/CSIRO-ARCCSS/ACCESS-CM2/historical/r1i1p1f1/Omon/thetao/gn/v20191108/thetao_Omon_ACCESS-CM2_historical_r1i1p1f1_gn_185001-185912.nc', 'sea_water_potential_temperature')

/g/data/r87/dbi599/miniconda3/envs/ocean/lib/python3.6/site-packages/iris/fileformats/cf.py:798: UserWarning: Missing CF-netCDF measure variable 'areacello', referenced by netCDF variable 'thetao'
  warnings.warn(message % (variable_name, nc_var_name))
/g/data/r87/dbi599/miniconda3/envs/ocean/lib/python3.6/site-packages/iris/fileformats/cf.py:798: UserWarning: Missing CF-netCDF measure variable 'volcello', referenced by netCDF variable 'thetao'
  warnings.warn(message % (variable_name, nc_var_name))


In [49]:
ref_cube

<iris 'Cube' of sea_water_potential_temperature / (degC) (time: 120; depth: 50; cell index along second dimension: 300; cell index along first dimension: 360)>

In [50]:
ref_cube.shape

(120, 50, 300, 360)

In [51]:
dset['temp_eta_smooth'].shape

(1980, 300, 360)

In [54]:
ref_cube.dim_coords

(DimCoord(array([  15.5,   45. ,   74.5,  105. ,  135.5,  166. ,  196.5,  227.5,
         258. ,  288.5,  319. ,  349.5,  380.5,  410. ,  439.5,  470. ,
         500.5,  531. ,  561.5,  592.5,  623. ,  653.5,  684. ,  714.5,
         745.5,  775.5,  805.5,  836. ,  866.5,  897. ,  927.5,  958.5,
         989. , 1019.5, 1050. , 1080.5, 1111.5, 1141. , 1170.5, 1201. ,
        1231.5, 1262. , 1292.5, 1323.5, 1354. , 1384.5, 1415. , 1445.5,
        1476.5, 1506. , 1535.5, 1566. , 1596.5, 1627. , 1657.5, 1688.5,
        1719. , 1749.5, 1780. , 1810.5, 1841.5, 1871. , 1900.5, 1931. ,
        1961.5, 1992. , 2022.5, 2053.5, 2084. , 2114.5, 2145. , 2175.5,
        2206.5, 2236.5, 2266.5, 2297. , 2327.5, 2358. , 2388.5, 2419.5,
        2450. , 2480.5, 2511. , 2541.5, 2572.5, 2602. , 2631.5, 2662. ,
        2692.5, 2723. , 2753.5, 2784.5, 2815. , 2845.5, 2876. , 2906.5,
        2937.5, 2967. , 2996.5, 3027. , 3057.5, 3088. , 3118.5, 3149.5,
        3180. , 3210.5, 3241. , 3271.5, 3302.5, 3332. ,

In [83]:
time_coord = iris.coords.DimCoord(dset['time'].values,
                                  standard_name='time',
                                  long_name='time',
                                  var_name='time',
                                  units=cf_units.Unit(dset['time'].units, calendar=dset['time'].calendar.lower()))

In [97]:
new_standard_name = dset['temp_eta_smooth'].long_name.replace(' ', '_')
iris.std_names.STD_NAMES[new_standard_name] = {'canonical_units': 'W m-2'}
new_cube = iris.cube.Cube(dset['temp_eta_smooth'].to_masked_array(),
                          standard_name=new_standard_name,
                          long_name=dset['temp_eta_smooth'].long_name,
                          var_name=dset['temp_eta_smooth'].name,
                          units='W m-2',
                          attributes=ref_cube.attributes,
                          dim_coords_and_dims=[(time_coord, 0),
                                               (ref_cube.dim_coords[-2], 1),
                                               (ref_cube.dim_coords[-1], 2)],
                          aux_coords_and_dims=[(ref_cube.aux_coords[0], (1, 2)),
                                               (ref_cube.aux_coords[1], (1, 2))])

In [98]:
new_cube

<iris 'Cube' of surface_smoother_for_temp / (W m-2) (time: 1980; cell index along second dimension: 300; cell index along first dimension: 360)>

In [40]:
dset['temp_eta_smooth'].coords

Coordinates:
  * xt_ocean  (xt_ocean) float64 -279.5 -278.5 -277.5 -276.5 ... 77.5 78.5 79.5
  * yt_ocean  (yt_ocean) float64 -77.88 -77.63 -77.38 ... 88.87 89.32 89.77
    geolat_t  (yt_ocean, xt_ocean) float32 -77.876625 -77.876625 ... 65.21044
    geolon_t  (yt_ocean, xt_ocean) float32 -279.5 -278.5 ... 79.973366 79.99112
  * time      (time) float64 15.5 45.0 74.5 ... 6.019e+04 6.022e+04 6.025e+04

In [101]:
dset['geolat_t'].values.shape

(300, 360)

In [103]:
ref_cube.coord('latitude').points.shape

(300, 360)

In [104]:
dset['geolat_t'].values[10, 10]

-75.29026

In [105]:
ref_cube.coord('latitude').points[10, 10]

-75.2902603149414

In [106]:
import numpy as np

In [107]:
np.allclose(ref_cube.coord('latitude').points, dset['geolat_t'].values)

True

In [108]:
dset['temp_eta_smooth'].ndim

3

In [109]:
ref_cube.ndim

4

In [112]:
dset['geolon_t'].values + 360

array([[ 80.5     ,  81.5     ,  82.5     , ..., 437.5     , 438.5     ,
        439.5     ],
       [ 80.5     ,  81.5     ,  82.5     , ..., 437.5     , 438.5     ,
        439.5     ],
       [ 80.5     ,  81.5     ,  82.5     , ..., 437.5     , 438.5     ,
        439.5     ],
       ...,
       [ 80.04428 ,  80.13287 ,  80.22153 , ..., 439.77847 , 439.86713 ,
        439.95572 ],
       [ 80.02658 ,  80.0798  ,  80.133026, ..., 439.86694 , 439.92023 ,
        439.97342 ],
       [ 80.00888 ,  80.02664 ,  80.0444  , ..., 439.9556  , 439.97336 ,
        439.99112 ]], dtype=float32)

In [113]:
ref_cube.coord('longitude').points.max()

359.9692687988281

In [114]:
ref_cube.coord('longitude').points.min()

0.02623666077852249

In [115]:
dset['geolon_t'].values.max()

79.99112

In [116]:
dset['geolon_t'].values.min()

-279.99112

In [117]:
test_lons = np.where(dset['geolon_t'].values < 0.0, dset['geolon_t'].values + 360, dset['geolon_t'].values)

In [118]:
test_lons

array([[80.5     , 81.5     , 82.5     , ..., 77.5     , 78.5     ,
        79.5     ],
       [80.5     , 81.5     , 82.5     , ..., 77.5     , 78.5     ,
        79.5     ],
       [80.5     , 81.5     , 82.5     , ..., 77.5     , 78.5     ,
        79.5     ],
       ...,
       [80.04428 , 80.13287 , 80.22153 , ..., 79.778465, 79.867134,
        79.95572 ],
       [80.02658 , 80.0798  , 80.133026, ..., 79.86696 , 79.92021 ,
        79.97341 ],
       [80.00888 , 80.02664 , 80.0444  , ..., 79.95559 , 79.973366,
        79.99112 ]], dtype=float32)

In [110]:
ref_cube.coord('longitude').points

masked_array(
  data=[[80.5       , 81.5       , 82.5       , ..., 77.5       ,
         78.5       , 79.5       ],
        [80.5       , 81.5       , 82.5       , ..., 77.5       ,
         78.5       , 79.5       ],
        [80.5       , 81.5       , 82.5       , ..., 77.5       ,
         78.5       , 79.5       ],
        ...,
        [80.04428101, 80.13287354, 80.2215271 , ..., 79.77846527,
         79.86713409, 79.95571899],
        [80.02658081, 80.07980347, 80.13302612, ..., 79.86695862,
         79.92021179, 79.97341156],
        [80.00888062, 80.02664185, 80.04440308, ..., 79.95558929,
         79.97336578, 79.99111938]],
  mask=False,
  fill_value=1e+20)